version: '3.7'
services:
  Webserver:
    container_name: nginx
    image: nginx
    volumes:
      - "../web:/usr/share/nginx/html"
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 400k
    restart: unless-stopped
  db:
    container_name: sqlserver2017
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
     - "1433:1433"
    volumes: 
     - "../DB:/root/dbfile:ro"
    environment:
     - SA_PASSWORD=MyPass@2020
     - ACCEPT_EULA=Y
     - TZ=Asia/Tokyo
     - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/mssql-tools/bin/
    command: bash -c
      "`sleep 20;sqlcmd -S localhost -U SA -P 'MyPass@2020' -i /root/dbfile/sql/createdb.sql;
      sqlcmd -S localhost -U SA -P 'MyPass@2020' -i /root/dbfile/sql/testdatainsert.sql` & 
      /opt/mssql/bin/sqlservr"
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 400k
    restart: unless-stopped

  websocket:
    build: 
      context: ./PyWebSocket
      args:
        - http_proxy=http://192.168.10.120:8080
    container_name: PyWebSocket
    ports:
      - "8080:8080"
    environment: 
      - ELANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    volumes:
      - "../py:/usr/local/bin/"
      #docker-composeをsudo経由で使う限りはホスト側のホームは/root/として扱われることを確認
      - "~/Picture/:/root/Picture/" 
    command: bash -c
      "python3 -u /usr/local/bin/dbwebskthub.py"
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 400k
    restart: unless-stopped
  samba:
    build: 
      context: ./samba
      dockerfile: ./dockerfile
    container_name: samba
    environment:
      TZ: Asia/Tokyo
    tmpfs:
      - /tmp
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - /home/banana2020:/mnt/banana:z
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 300k
    restart: unless-stopped